# Generated by Django 4.0.4 on 2022-04-27 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='songs',
        ),
    ]
